import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";
import styeles from "./Header.module.css";

const inter = Inter({ subsets: ["latin"] });

export function Header() {
  return (
    <>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styeles.header}>
        <Link href={"/"} className={styeles.anchor}>Index</Link>
        <Link href={"/about"} className={styeles.anchor}>About</Link>
      </header>
    </>
  );
}
